# Generated by Django 4.2.5 on 2024-04-09 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('about_me', models.CharField(max_length=200, verbose_name='about_me')),
                ('is_webdesigner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.CharField(max_length=2000, verbose_name='Description of the model')),
                ('about', models.CharField(max_length=1)),
                ('contact_email', models.CharField(max_length=1)),
                ('Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtPortfolioApp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('is_for_sale', models.BooleanField()),
                ('price', models.FloatField()),
                ('needs_to_be_added', models.BooleanField(default=True)),
                ('size_inches', models.CharField(max_length=200, verbose_name='size in inches')),
                ('image', models.ImageField(upload_to='images/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtPortfolioApp.portfolio')),
            ],
        ),
    ]
